#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "arm-fsl-linux-gnueabi-gcc -O"
  #define PLATFORM "dist"
  #define DATE "Thu May 28 14:59:31 CST 2015"
#endif
